language: generic
env:
  global:
    secure: VtL2QFiVgbcL0lVeUbnF4wwmfKBNTIbeYiCpHkYYZhFKGtC7sbKfRXhXFdwp2tXfPjJEJKkJo2cMdMyRI10CvB9U65Z7h7pAx0sZ2DwoloVdjT8f2iqabj9xc5HDYRi2cx+WvbVWXeI+jFQx1S2mlpTMOzN6qqPjLIIjyni1rmA+P3v2rAXYkVslp2QAWMJCSY9acH3NOth8KGBOUt6s9eJ0MUSuA2DRrSbinLq0ry4S9vs5HM8oRMggU0YUfA99NYJjq3c0FEp453M7fmKbPRh/71geLtm+0vm2HjIH7QkBAdS+Jc3eJoxcaMvj9e3lb3wwPSoE+6YKctMD4h0qhvv+x4fz1imrwUT/pPt21pkUvJBD2CDebNl/BUOwvQZYxT58jSa/n/+2wza/Oaeus5nztZnJ+Ufoz3xsMuUS8SfzLX3rhTfGXZxsuYkUVOt3aOdjvLl6gkF8reBFPOteSrv1Hi4L7EKnIsMqw5FaAC1co89WIezaBJ1H/qS0czu+VAghU7GfMiyIgmi2FwP3pFIRdktl5JP6K/vzFv/01aBQuBESM76qykwu2HhzzUsFKcYgICgvpbyUI5iZIk3Iiu3jaA7h38pUR60oXOSVApIqgtrCoqPZCrBCkGnVFLf9N5RMZMOdI1Yh7FFLWgjFkFQQg0RH94qrg47qCEoCy9c=
deploy:
  provider: script
  script: bash upload.sh
  on:
    branch: master